### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by zuurw** [castorini/parrot#4]
Hello, Im a Graphic Designer that likes to contribute to open source projects, I saw that this project is new, can you tell me more about it?
If you like it will be a pleasure to me to design a logo for parrot

Greetings.

**Comment by daemon** [comment]
Thanks for your interest. Parrot is a tool for creating small-scale speech corpora by using online resources, like Microsoft TTS, IBM Watson, and YouTube. A logo isn't high priority, but we're interested in seeing what you can create.

**Comment by zuurw** [comment]
Hi @daemon, do you have an idea for the logo? do you have any request to make? what colors do you prefer?

Cheers!

**Comment by daemon** [comment]
I guess a graphic that combines a parrot with an audio waveform graph, but feel free to design as you see fit. I have no color preference.

Thanks again.

**Comment by zuurw** [comment]
Hello here is the design that I create for this project. What do you think?

![parrot player](https://user-images.githubusercontent.com/40801473/42345868-aad04cee-8098-11e8-8ea9-e2950c2aa2c6.png)

**Comment by daemon** [comment]
The logo at row 1, column 2 is great! Thanks!

[Honk](https://github.com/castorini/honk), the other project that we're working on, could use a graphic as well. I was thinking something along the lines of Parrot's logo, but with a goose instead?

Thanks again!

**Comment by zuurw** [comment]
Im happy that you like it, so I will make a pull request with the logo files.

I can make also the logo for Honk, but I notice that it have no license like parrot, can you had one, because I only design for projects that have license.

Best regards!

**Comment by daemon** [comment]
Added MIT license, thanks for pointing that out.

**Comment by tuzhucheng** [comment]
This is amazing, thanks @zuurw!

**Comment by daemon** [comment]
Closed by PR #6.
